#!/bin/bash

exec > >(tee -i $HOME/codespaces-post-start.log)
exec 2>&1
set -e
set -x

ROOT=$(cd $(dirname "$BASH_SOURCE")/..; pwd)
INSTALL="$ROOT/bin/install"
DOTFILES="$ROOT/wincent"

cd $DOTFILES

git submodule update --init --recursive

NON_INTERACTIVE=1 "$INSTALL" "$@"
