#!/bin/bash

set -e

ROOT=$(cd $(dirname "$BASH_SOURCE")/..; pwd)
INSTALL="$ROOT/bin/install"
DOTFILES="$ROOT/wincent"

cd $DOTFILES

git submodule update --init

NON_INTERACTIVE=1 "$INSTALL"

ln -sf "${ROOT}/.zshenv.d/locale.zsh" ~/.zshenv.d/locale.zsh
ln -sf "${ROOT}/.zshrc.local" ~/.zshrc.local
ln -sf "${ROOT}/.tmux-local.conf" ~/.tmux-local.conf
